### ISSUE TITLE
SASS formatting

### ISSUE THREAD

**Issue by phette23** [cca/libraries_wagtail#60]
the SASS files from Torchbox don't pass scss-lint, they have inconsistent 2-space indenting. Code like this:

```scss
.blog-post__one {
  // only indented 2 spaces, should be 4
  font-size: 14px;
}
  .blog-post__title {
    // despite not being nested under .blog-post__one this is indented as if it is
    font-weight: 700;
  }
```

Run `scss-lint` to identify more problems.
